#cloud-config
datasource:
 Ec2:
  strict_id: false
ssh_pwauth: no
users:
  - name: keglia
    groups: sudo
    shell: /bin/bash
    sudo: 'ALL=(ALL) NOPASSWD:ALL'
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOUoWCjArsGVdy2LtLULp/Fcp2mwl15vtcE1guQzeIqT xp@LAPTOP-08A5M294
runcmd: []      
